[project]
name = "pypline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.1",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
